### PR TITLE
Fix undefined method 'bytesize' for nil in callback phase

### PR DESCRIPTION
**Pull request by nickstanish**
v1.9.0 appears to have introduced a NoMethodError if the callback is performed without the stored state in the session

(ran into this while working on a separate patch)

### CODE REVIEW

**Review by sj-ransom — APPROVED** [review]

**Comment by dgsierra** [comment]
Confirming this on 1.9.0, with a bisect and one detail that I think makes the impact
broader than the title suggests.

**It's a regression from #174.** Before that PR the check was:

```ruby
request.params["state"] != session.delete("omniauth.state")
```

which is nil-safe. #174 replaced it with `secure_compare`, whose first line is
`return false unless string_a.bytesize == string_b.bytesize` (`oauth2.rb:149`). So the
timing-attack hardening introduced a nil crash on the very path it was hardening.

**Repro, no app required:**

```ruby
require "omniauth"
require "omniauth-oauth2"

stack = OmniAuth::Builder.new(->(_e) { [404, {}, []] }) { provider :oauth2, "id", "secret" }
env   = Rack::MockRequest.env_for("/auth/oauth2/callback?state=x", "rack.session" => {})
stack.call(env)
```

**Two outcomes, depending on `RACK_ENV`:**

| `RACK_ENV` | Result |
|---|---|
| `development` (the default `failure_raise_out_environments`) | `NoMethodError: undefined method 'bytesize' for nil` raised out — a 500 |
| anything else | `302 /auth/failure?message=undefined+method+%27bytesize%27+for+nil&strategy=oauth2` |

The second row is the one worth emphasising. It doesn't crash, because `Strategy#call!`
blanket-rescues `StandardError` and calls `fail!(e.message, e)` — so the raw Ruby error
message ends up in a user-facing redirect URL, and `omniauth.error.type` becomes
`:"undefined method 'bytesize' for nil"` instead of `:csrf_detected`. Any app that
branches on the failure reason reads a rejected CSRF check as an internal error, and it
only stays a non-500 because of a rescue that `callback_phase`'s own rescue list
(`OAuth2::Error`, `CallbackError`, timeouts, `SocketError`) clearly wasn't written to
depend on.

A callback with no stored state is entirely routine, not just a scanner hitting the
endpoint: a session cookie that expired mid-flow, a stale bookmarked callback URL, or a
cross-site `form_post` callback (Sign in with Apple) where the session cookie is
`SameSite=Lax` and therefore withheld by the browser. None of those should surface as an
internal error.

**This patch looks correct to me** — including the part that is easy to miss, hoisting
`session.delete` out of the `||` so a blank `state` param still consumes the stored
state. Would be good to see it land.

<sub>Not a request to change this PR, just noting it for completeness: downstream we
guarded `secure_compare` itself (`return false if string_a.nil? || string_b.nil?`)
rather than `callback_phase`, purely because it's easier to carry as a `prepend` until
this merges. It does not cover the `session.delete` hoisting above.</sub>
